// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASNTvFR0fhoCvBoJdUBSbog9W5ep0useU',
    appId: '1:952589533851:web:5b3dc551473bb69f54fc3e',
    messagingSenderId: '952589533851',
    projectId: 'fic12-3deb6',
    authDomain: 'fic12-3deb6.firebaseapp.com',
    storageBucket: 'fic12-3deb6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvjix0Ty8YQuss42O-36NXafmFHcxwYAs',
    appId: '1:952589533851:android:377cd553300d425654fc3e',
    messagingSenderId: '952589533851',
    projectId: 'fic12-3deb6',
    storageBucket: 'fic12-3deb6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1hGhnZvCzej-7Et8Kgu6JI3ncTxtoW_E',
    appId: '1:952589533851:ios:4f57c175df2567a254fc3e',
    messagingSenderId: '952589533851',
    projectId: 'fic12-3deb6',
    storageBucket: 'fic12-3deb6.appspot.com',
    iosBundleId: 'com.example.flutterOnlineshopApp',
  );
}
